import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import { 
  X, Download, Printer, ZoomIn, ZoomOut, Maximize2, Minimize2, 
  ChevronLeft, ChevronRight, FileText, Check, ShieldCheck 
} from 'lucide-react';

interface PdfViewerProps {
  title: string;
  fileName: string;
  boardName: string;
  examTitle: string;
  subjectCode?: string;
  subjectName: string;
  maxMarks: number;
  durationText: string;
  instructions?: string[];
  sections?: {
    title: string;
    desc?: string;
    questions: string[];
  }[];
  contentString?: string;
  onClose: () => void;
  watermarkText?: string;
  autoDownload?: boolean;
}

export default function PdfViewer({
  title,
  fileName,
  boardName,
  examTitle,
  subjectCode,
  subjectName,
  maxMarks,
  durationText,
  instructions = [],
  sections = [],
  contentString,
  onClose,
  watermarkText = 'Ishwar Hiremath',
  autoDownload = false
}: PdfViewerProps) {
  const [zoom, setZoom] = useState<number>(100);
  const [isFullscreen, setIsFullscreen] = useState<boolean>(false);
  const [isDownloading, setIsDownloading] = useState<boolean>(false);
  const [isPrinting, setIsPrinting] = useState<boolean>(false);

  // Auto download trigger when component mounts
  useEffect(() => {
    if (autoDownload) {
      const timer = setTimeout(() => {
        handleDownloadPdf();
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [autoDownload]);

  // Download real PDF using jsPDF
  const handleDownloadPdf = () => {
    setIsDownloading(true);
    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
      });

      const pageWidth = 210;
      const pageHeight = 297;
      const margin = 15;
      const contentWidth = pageWidth - 2 * margin;
      
      let pageNum = 1;

      // Draw custom border and watermark on current page
      const preparePage = () => {
        // Double frame borders for official aesthetic
        doc.setDrawColor(180, 180, 180);
        doc.setLineWidth(0.2);
        doc.rect(8, 8, pageWidth - 16, pageHeight - 16);
        
        doc.setDrawColor(0, 0, 0);
        doc.setLineWidth(0.5);
        doc.rect(10, 10, pageWidth - 20, pageHeight - 20);

        // Watermarks - strictly locked to "Ishwar Hiremath"
        doc.saveGraphicsState();
        doc.setTextColor(242, 242, 242); // Light grey watermark as requested
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(36);
        
        // Render 3 diagonal watermarks across the page
        const wText = 'Ishwar Hiremath';
        doc.text(wText, 35, 75, { angle: 45 });
        doc.text(wText, 35, 155, { angle: 45 });
        doc.text(wText, 35, 235, { angle: 45 });
        doc.restoreGraphicsState();

        // Page Number at bottom
        doc.setFont('Helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text(`Page ${pageNum} - Generated by Ishwar Hiremath Academy`, pageWidth / 2, pageHeight - 13, { align: 'center' });
      };

      preparePage();

      let currentY = 18;

      // 1. Title Board Header
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      doc.text(boardName.toUpperCase(), pageWidth / 2, currentY, { align: 'center' });
      currentY += 6;

      doc.setFontSize(10);
      doc.text(examTitle.toUpperCase(), pageWidth / 2, currentY, { align: 'center' });
      currentY += 8;

      // Header Separator line
      doc.setLineWidth(0.4);
      doc.line(12, currentY, pageWidth - 12, currentY);
      currentY += 6;

      // Subject Name and Code
      doc.setFontSize(9);
      const subjectFullText = subjectCode ? `SUBJECT: ${subjectCode} - ${subjectName}` : `SUBJECT: ${subjectName}`;
      doc.text(subjectFullText.toUpperCase(), 15, currentY);
      currentY += 5;

      // Marks and Duration row
      doc.text(`MAX MARKS: ${maxMarks}`, 15, currentY);
      doc.text(`TIME: ${durationText}`, pageWidth - 15 - doc.getTextWidth(`TIME: ${durationText}`), currentY);
      currentY += 5;

      // Double line separator
      doc.line(12, currentY, pageWidth - 12, currentY);
      currentY += 8;

      // 2. General Instructions
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('GENERAL INSTRUCTIONS:', 15, currentY);
      currentY += 5;

      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(40, 40, 40);

      instructions.forEach((ins, idx) => {
        const fullInsText = `${idx + 1}. ${ins}`;
        const lines = doc.splitTextToSize(fullInsText, contentWidth - 4);
        lines.forEach((line: string) => {
          if (currentY > pageHeight - 20) {
            pageNum++;
            doc.addPage();
            preparePage();
            currentY = 20;
          }
          doc.text(line, 15, currentY);
          currentY += 4.5;
        });
      });

      currentY += 5;

      if (contentString) {
        doc.setFont('Courier', 'normal');
        doc.setFontSize(8.5);
        doc.setTextColor(30, 30, 30);

        const rawLines = contentString.split('\n');
        rawLines.forEach((lineText: string) => {
          const lines = doc.splitTextToSize(lineText || " ", contentWidth);
          lines.forEach((line: string) => {
            if (currentY > pageHeight - 20) {
              pageNum++;
              doc.addPage();
              preparePage();
              currentY = 20;
              doc.setFont('Courier', 'normal');
              doc.setFontSize(8.5);
              doc.setTextColor(30, 30, 30);
            }
            doc.text(line, 15, currentY);
            currentY += 4.5;
          });
        });
      } else {
        // 3. Sections and Questions
        sections.forEach((sec) => {
          // Section Title
          if (currentY > pageHeight - 35) {
            pageNum++;
            doc.addPage();
            preparePage();
            currentY = 20;
          }

          currentY += 4;
          doc.setFont('Helvetica', 'bold');
          doc.setFontSize(9.5);
          doc.setTextColor(0, 0, 0);
          doc.text(sec.title, 15, currentY);
          currentY += 5;

          if (sec.desc) {
            doc.setFont('Helvetica', 'oblique');
            doc.setFontSize(8.5);
            doc.setTextColor(80, 80, 80);
            const descLines = doc.splitTextToSize(sec.desc, contentWidth);
            descLines.forEach((line: string) => {
              if (currentY > pageHeight - 20) {
                pageNum++;
                doc.addPage();
                preparePage();
                currentY = 20;
              }
              doc.text(line, 15, currentY);
              currentY += 4.5;
            });
            currentY += 3;
          }

          doc.setFont('Helvetica', 'normal');
          doc.setFontSize(8.5);
          doc.setTextColor(30, 30, 30);

          sec.questions.forEach((q, qidx) => {
            const fullQuestionText = `${qidx + 1}. ${q}`;
            const qLines = doc.splitTextToSize(fullQuestionText, contentWidth - 4);
            
            qLines.forEach((line: string) => {
              if (currentY > pageHeight - 20) {
                pageNum++;
                doc.addPage();
                preparePage();
                currentY = 20;
                doc.setFont('Helvetica', 'normal');
                doc.setFontSize(8.5);
                doc.setTextColor(30, 30, 30);
              }
              doc.text(line, 15, currentY);
              currentY += 5;
            });
            currentY += 2; // small space after question
          });

          currentY += 3;
        });
      }

      doc.save(fileName);
    } catch (err) {
      console.error('Error generating watermarked PDF:', err);
      alert('Could not compile PDF document. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };

  // Simulated browser print triggers window.print
  const handlePrint = () => {
    setIsPrinting(true);
    setTimeout(() => {
      window.print();
      setIsPrinting(false);
    }, 1000);
  };

  return (
    <div className={`fixed inset-0 z-50 flex flex-col bg-slate-950/95 backdrop-blur-md animate-fade-in ${
      isFullscreen ? 'p-0' : 'p-2 sm:p-6 lg:p-8'
    }`}>
      {/* ADOBE ACROBAT / CR-PDF INSPIRED STYLISH TOOLBAR */}
      <div className="flex flex-col md:flex-row items-center justify-between bg-slate-900 border-2 border-black rounded-3xl p-4 gap-4 shadow-[4px_4px_0px_rgba(0,0,0,1)] text-white w-full max-w-7xl mx-auto mb-4">
        {/* Document Info */}
        <div className="flex items-center space-x-3 w-full md:w-auto">
          <div className="bg-red-500 text-white p-2 rounded-xl border border-black shadow-[2px_2px_0px_rgba(0,0,0,1)] shrink-0">
            <FileText className="h-5 w-5" />
          </div>
          <div className="truncate">
            <h3 className="font-sans font-black text-xs sm:text-sm tracking-tight text-white uppercase truncate">
              {title}
            </h3>
            <p className="text-[10px] text-slate-400 font-mono flex items-center gap-1 mt-0.5">
              <ShieldCheck className="h-3 w-3 text-yellow-400 inline" />
              <span>Ishwar Hiremath Secured PDF Engine</span>
            </p>
          </div>
        </div>

        {/* Toolbar Middle Controls (Zoom & Navigation) */}
        <div className="flex items-center space-x-2 sm:space-x-4">
          {/* Zoom Buttons */}
          <div className="flex items-center space-x-1 bg-slate-950 px-2 py-1 rounded-xl border border-slate-800">
            <button 
              onClick={() => setZoom(Math.max(50, zoom - 10))}
              className="p-1 text-slate-400 hover:text-white rounded transition cursor-pointer"
              title="Zoom Out"
            >
              <ZoomOut className="h-4 w-4" />
            </button>
            <span className="text-[10px] font-mono text-slate-300 w-12 text-center select-none font-bold">
              {zoom}%
            </span>
            <button 
              onClick={() => setZoom(Math.min(150, zoom + 10))}
              className="p-1 text-slate-400 hover:text-white rounded transition cursor-pointer"
              title="Zoom In"
            >
              <ZoomIn className="h-4 w-4" />
            </button>
          </div>

          {/* Full Screen Toggle */}
          <button
            onClick={() => setIsFullscreen(!isFullscreen)}
            className="p-2 bg-slate-950 hover:bg-slate-850 text-slate-300 hover:text-white border border-slate-800 rounded-xl transition cursor-pointer"
            title={isFullscreen ? 'Exit Fullscreen' : 'Enter Fullscreen'}
          >
            {isFullscreen ? <Minimize2 className="h-4 w-4" /> : <Maximize2 className="h-4 w-4" />}
          </button>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-end space-x-2 w-full md:w-auto">
          {/* Print button */}
          <button
            onClick={handlePrint}
            className="px-3.5 py-2 bg-slate-950 hover:bg-slate-850 text-slate-100 rounded-xl text-xs font-black border-2 border-black shadow-[2px_2px_0px_rgba(0,0,0,1)] active:translate-x-[1px] active:translate-y-[1px] transition-all cursor-pointer flex items-center gap-1.5"
          >
            <Printer className="h-4 w-4 text-slate-400" />
            <span>Print</span>
          </button>

          {/* Download Real Watermarked PDF */}
          <button
            onClick={handleDownloadPdf}
            disabled={isDownloading}
            className="px-4 py-2 bg-emerald-500 hover:bg-emerald-400 text-slate-950 rounded-xl text-xs font-black border-2 border-black shadow-[3px_3px_0px_rgba(0,0,0,1)] active:translate-x-[2px] active:translate-y-[2px] active:shadow-[1px_1px_0px_rgba(0,0,0,1)] disabled:opacity-50 transition-all cursor-pointer flex items-center gap-2"
          >
            <Download className="h-4 w-4 stroke-[3px]" />
            <span>{isDownloading ? 'Compiling PDF...' : 'Download PDF'}</span>
          </button>

          {/* Close button */}
          <button
            onClick={onClose}
            className="p-2 bg-rose-600 hover:bg-rose-500 text-white rounded-xl border-2 border-black shadow-[2px_2px_0px_rgba(0,0,0,1)] cursor-pointer transition-all"
            title="Exit PDF Reader"
          >
            <X className="h-4 w-4 font-bold" />
          </button>
        </div>
      </div>

      {/* RENDER VIEWPORT (WATERMARKED CLAY BACKGROUND) */}
      <div className="flex-1 overflow-auto bg-slate-950/80 rounded-3xl p-4 md:p-8 flex items-start justify-center border-2 border-black max-w-7xl mx-auto w-full shadow-inner relative select-none">
        {/* Main Document Layout conforming to A4 sizing based on Zoom state */}
        <div 
          style={{ transform: `scale(${zoom / 100})`, transformOrigin: 'top center' }}
          className="bg-white text-slate-950 shadow-[0_20px_50px_rgba(0,0,0,0.5)] border-4 border-black transition-transform duration-200 ease-out max-w-full relative shrink-0 p-8 sm:p-14 mb-16 overflow-hidden rounded-md"
        >
          {/* Sizing constraints for exact A4 paper simulation on desktop */}
          <div className="w-[100%] sm:w-[170mm] min-h-[240mm] relative">
            
            {/* STYLISH DIAGONAL WATERMARK AT 45 DEGREE ANGLE */}
            <div className="absolute inset-0 grid grid-cols-1 grid-rows-3 pointer-events-none select-none opacity-5 overflow-hidden">
              <div className="flex items-center justify-center text-slate-950 font-sans font-black tracking-widest uppercase text-3xl sm:text-5xl -rotate-45 transform">
                Ishwar Hiremath
              </div>
              <div className="flex items-center justify-center text-slate-950 font-sans font-black tracking-widest uppercase text-3xl sm:text-5xl -rotate-45 transform">
                Ishwar Hiremath
              </div>
              <div className="flex items-center justify-center text-slate-950 font-sans font-black tracking-widest uppercase text-3xl sm:text-5xl -rotate-45 transform">
                Ishwar Hiremath
              </div>
            </div>

            {/* Content Container (Prints nicely, styled professionally) */}
            <div className="relative z-10 space-y-6 font-serif">
              {/* Exam Header */}
              <div className="text-center space-y-2 border-b-2 border-slate-950 pb-4">
                <span className="text-[10px] font-mono tracking-widest uppercase font-bold text-slate-600 block">{boardName}</span>
                <h2 className="text-sm sm:text-base font-bold uppercase tracking-tight text-slate-900">{examTitle}</h2>
                
                <div className="flex flex-col sm:flex-row items-center justify-between text-xs font-mono font-bold text-slate-700 pt-2 px-1 gap-1.5 border-t border-dashed border-slate-300">
                  <span>{subjectCode ? `SUBJECT CODE: ${subjectCode}` : `EXAM: ${subjectName}`}</span>
                  <span>{subjectName.toUpperCase()}</span>
                </div>
                <div className="flex flex-row items-center justify-between text-xs font-mono font-bold text-slate-700 px-1 pt-1">
                  <span>MAX MARKS: {maxMarks}</span>
                  <span>TIME ALLOWED: {durationText}</span>
                </div>
              </div>

              {/* Instructions Section */}
              {instructions && instructions.length > 0 && (
                <div className="space-y-2 bg-slate-55 p-4 rounded-xl border border-slate-300 font-sans">
                  <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">Instructions to Candidates:</h3>
                  <ol className="list-decimal pl-4 text-[11px] sm:text-xs text-slate-700 space-y-1">
                    {instructions.map((ins, idx) => (
                      <li key={idx} className="leading-relaxed">{ins}</li>
                    ))}
                  </ol>
                </div>
              )}

              {/* Sections Map or Raw Content String */}
              {contentString ? (
                <div className="space-y-4 text-[11px] sm:text-xs leading-relaxed text-slate-900 font-mono bg-slate-50 border border-slate-200 p-4 rounded-xl whitespace-pre-wrap select-text text-left">
                  {contentString}
                </div>
              ) : (
                <div className="space-y-8 text-[11px] sm:text-xs leading-relaxed text-slate-900">
                  {sections.map((sec, sidx) => (
                    <div key={sidx} className="space-y-4">
                      <div className="border-b-2 border-slate-900 pb-1 pt-2">
                        <h4 className="font-bold text-xs uppercase tracking-wide text-slate-950">{sec.title}</h4>
                        {sec.desc && <p className="text-[11px] italic text-slate-600 font-sans mt-1">{sec.desc}</p>}
                      </div>

                      <div className="space-y-3 font-serif">
                        {sec.questions.map((q, qidx) => (
                          <div key={qidx} className="flex items-start space-x-3 pl-1">
                            <span className="font-bold text-slate-950">{qidx + 1}.</span>
                            <span className="flex-1 whitespace-pre-wrap">{q}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* Official Seal Footer info */}
              <div className="pt-8 border-t border-slate-300 text-center text-[10px] text-slate-500 font-mono">
                <p>© ISHWAR HIREMATH ACADEMY, EDUCURIA BOARD. ALL RIGHTS RESERVED.</p>
                <p className="text-[8px] tracking-wider text-slate-400 mt-0.5">THIS IS AN OFFICIAL SECURED TESTING DOCUMENT. FRAUDULENT USE IS STRICTLY PROHIBITED.</p>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
